import { afterAll, beforeAll, beforeEach, expect, it, vi } from "vitest";
import { databaseSuite } from "@test/database-suite";

/**
 * An offline send, replayed, against a real Postgres.
 *
 * The failure this pins down: the service worker holds a queued send in
 * IndexedDB and re-POSTs it when the network returns. If the first attempt
 * reached the server and the *response* was the thing that got lost, the
 * replay is indistinguishable from a first attempt — and the idempotency key
 * used to be derived from a draft id the server minted, so a queued body with
 * no draft yet minted a new row and a new key every time. The message went out
 * twice and appeared twice in Sent.
 *
 * `clientKey` is generated by the browser before the request is queued, which
 * makes it the message's identity across replays. This asserts what that buys:
 * one row and one provider call, however many times the worker retries.
 *
 * `sendOne` is mocked because the point is how many times it is called, not
 * what Resend does with it. Everything below it — the keyed upsert, the claim,
 * the unique index on `client_key` — is real.
 */
const mocks = vi.hoisted(() => ({
  // Parameters declared so the recorded call can be inspected: the second
  // argument is where the idempotency key rides.
  sendOne: vi.fn(async (_message: unknown, _options?: { idempotencyKey?: string }) => ({
    id: "msg_replay_test",
    error: null as string | null,
  })),
}));

vi.mock("next/cache", () => ({ revalidatePath: vi.fn() }));
vi.mock("@sendstack/auth", () => ({
  requireSession: vi.fn(async () => ({ user: { id: "test-user" } })),
  // The Identity send gate. Unenforced in production and irrelevant to what
  // this suite proves, so it allows; `policy-gate.integration.test.ts` is
  // where its refusal path is exercised for real.
  assertCanSend: vi.fn(async () => null),
}));
vi.mock("@sendstack/config", async (importOriginal) => {
  const actual = await importOriginal<typeof import("@sendstack/config")>();
  return {
    ...actual,
    getConfig: vi.fn(async () => ({
      appName: "Test",
      appUrl: "http://localhost:3000",
      primaryColor: "#000000",
      postalAddress: null,
      emailTemplate: "simple",
      // Deliberately mixed case: the stored sender must come out normalised
      // whatever the operator typed into Settings. See the assertion below.
      resend: { fromEmail: "Test@Example.com", fromName: "Test", apiKey: null },
    })),
  };
});
vi.mock("@sendstack/email", async (importOriginal) => {
  const actual = await importOriginal<typeof import("@sendstack/email")>();
  return {
    ...actual,
    sendOne: mocks.sendOne,
    // Rendering a React Email template per call is slow and is not what is
    // under test; the body only has to be non-empty to reach the send.
    currentBrand: vi.fn(async () => ({
      appName: "Test",
      appUrl: "http://localhost:3000",
      primaryColor: "#000000",
      logoUrl: null,
      postalAddress: null,
    })),
    renderCampaignEmail: vi.fn(async () => ({
      html: "<p>Queued while offline</p>",
      text: "Queued while offline",
    })),
  };
});

const clientKey = `11111111-1111-4111-8111-${Date.now().toString().slice(-12)}`;
/** `outbound_messages.created_by` is a real foreign key, so the author exists. */
const userId = `test-user-${Date.now().toString(36)}`;

const queued = {
  clientKey,
  to: "replay-target@example.com",
  subject: "Sent from a tunnel",
  html: "<p>Queued while offline</p>",
  text: "Queued while offline",
};

databaseSuite("an offline send replayed with the same client key", { timeout: 30_000 }, () => {
  beforeEach(() => {
    mocks.sendOne.mockClear();
  });

  beforeAll(async () => {
    const { db, sql } = await import("@sendstack/db");
    const { requireSession } = await import("@sendstack/auth");
    vi.mocked(requireSession).mockResolvedValue({ user: { id: userId } } as never);
    await db.execute(sql`
      INSERT INTO "user" (id, name, email)
      VALUES (${userId}, 'Replay Test', ${`${userId}@example.test`})
      ON CONFLICT (id) DO NOTHING
    `);
  });

  afterAll(async () => {
    const { db, sql } = await import("@sendstack/db");
    /**
     * Cleaned up by author *and* by provider id, not by `client_key` alone.
     *
     * Deleting on the key assumes the code under test stored it — which is
     * exactly what fails when someone breaks the client-key handling on
     * purpose to check that this suite catches it. Those runs left rows with
     * a null key behind, and three of them sat in a real database until
     * somebody went looking. A cleanup predicate must not depend on the
     * behaviour the test is trying to disprove.
     */
    await db.execute(sql`DELETE FROM outbound_messages WHERE created_by = ${userId}`);
    await db.execute(sql`DELETE FROM outbound_messages WHERE provider_message_id = 'msg_replay_test'`);
    await db.execute(sql`DELETE FROM "user" WHERE id = ${userId}`);
  });

  it("sends once and keeps one row, however many times the worker retries", async () => {
    const { sendSingleEmail } = await import("./compose");
    const { db, sql } = await import("@sendstack/db");

    const first = await sendSingleEmail(queued);
    const second = await sendSingleEmail(queued);
    const third = await sendSingleEmail(queued);

    expect(first.ok, JSON.stringify(first)).toBe(true);
    expect(second.ok).toBe(true);
    expect(third.ok).toBe(true);

    // The replays answer with the same row the first attempt created.
    if (first.ok && second.ok && third.ok) {
      expect(second.id).toBe(first.id);
      expect(third.id).toBe(first.id);
    }

    // One provider call. The replays saw a row that was already `sent` and
    // returned that answer late rather than mailing anybody again.
    expect(mocks.sendOne).toHaveBeenCalledTimes(1);

    /**
     * And that call carried the browser's key, not the row's.
     *
     * Belt and braces for the case the row-level claim loses a race: two
     * replays arriving at the same instant both find a row that is not yet
     * `sent` and both call the provider. Resend collapses them only because
     * the key is derived from `clientKey`, which is identical across replays,
     * where the old `compose:${draftId}` was not.
     */
    expect(mocks.sendOne.mock.calls[0]?.[1]?.idempotencyKey).toBe(`compose:${clientKey}`);

    const [row] = Array.from(
      await db.execute<{ n: number; from_email: string }>(
        sql`SELECT count(*)::int AS n, min(from_email) AS from_email
            FROM outbound_messages WHERE client_key = ${clientKey}`,
      ),
    );
    expect(row?.n).toBe(1);

    /**
     * And the sender was normalised on the way in — invariant 6.
     *
     * This action had a third address parser, `bareAddress`, which stripped
     * the angle brackets and trimmed but never lowercased, so a sender
     * configured as `Hello@Domain.com` was stored mixed-case here while every
     * other address in the system is normalised at its boundary. It is
     * `parseAddress` from `@sendstack/shared` now, which is where that rule
     * already lived.
     */
    expect(row?.from_email).toBe("test@example.com");
  });
});
